language: r
cache: packages

r_packages: covr

env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes"
     - R_CHECK_ARGS="--no-build-vignettes --as-cran"

after_success:
- Rscript -e 'library(covr); codecov()'
